### ISSUE TITLE
Issue with www.youtube.com

### ISSUE THREAD

**Issue by benio075** [fire015/adblocker-notice-removal#100]
https://www.youtube.com/watch?v=X1FbwooXssQ&t=3429s&ab_channel=Wendigoon

Extension version: 1.2.31

Which country are you browsing from? brazil
Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![image](https://github.com/fire015/adblocker-notice-removal/assets/109307953/5e72779e-37d4-476b-80c2-da1f8b9c676d)

**Comment by fire015** [comment]
Unfortunately I could not replicate this!
