### ISSUE TITLE
Issue with u.m3uiptv.com

### ISSUE THREAD

**Issue by GobGobGobble** [fire015/adblocker-notice-removal#101]
https://u.m3uiptv.com/free-iptv-links-m3u-playlists-updated-19-aug-2023/

Extension version: 1.2.31

Which country are you browsing from? USA

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

![image](https://github.com/fire015/adblocker-notice-removal/assets/142565534/833f0ba7-734d-466b-9069-96e38b728e60)

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
