### ISSUE TITLE
Issue with rollercoin.com

### ISSUE THREAD

**Issue by Devian34** [fire015/adblocker-notice-removal#103]
https://rollercoin.com/game

Extension version: 1.2.32
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

Which country are you browsing from? [ANSWER HERE]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
