### ISSUE TITLE
Issue with crosswordspin.com

### ISSUE THREAD

**Issue by kraen** [fire015/adblocker-notice-removal#104]
https://crosswordspin.com/create

Extension version: 1.2.32
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

Which country are you browsing from? Denmark

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

![image](https://github.com/fire015/adblocker-notice-removal/assets/8984335/546c063a-7666-4ce7-97fc-e88212d37b65)

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
