### ISSUE TITLE
Issue with www.olarila.com

### ISSUE THREAD

**Issue by Trijal08** [fire015/adblocker-notice-removal#105]
https://www.olarila.com/

Extension version: 1.2.32
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 YandexBrowser/23.7.3.823 Yowser/2.5 Safari/537.36

Which country are you browsing from? [Canada]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![Screenshot 2023-08-25 115550](https://github.com/fire015/adblocker-notice-removal/assets/97483939/97ca9df8-f1af-41de-a2c0-2f291ad44089)

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
