### ISSUE TITLE
Issue with polytoria.com

### ISSUE THREAD

**Issue by RickGotTaken** [fire015/adblocker-notice-removal#106]
https://polytoria.com

Extension version: 1.2.34
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 OPR/101.0.0.0

Which country are you browsing from? United Kingdom

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![image](https://github.com/fire015/adblocker-notice-removal/assets/96528846/e57f7a3c-29cf-4d70-a18d-301edc2a8434)

**Comment by fire015** [comment]
Should be fixed in the next version, thanks!

**Comment by RickGotTaken** [comment]
> Should be fixed in the next version, thanks!

No problem!
