### ISSUE TITLE
Issue with megaup.net

### ISSUE THREAD

**Issue by JayTheTechGuy** [fire015/adblocker-notice-removal#107]
https://megaup.net/XCap/Mario_Golf_Super_Rush_(NSP)(Base_Game)(Verified).rar

Extension version: 1.2.35
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.76

Which country are you browsing from? [ANSWER HERE]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Unfortunately this cannot be fixed by this extension as hiding the adblocker notice will not display the download button, so doesn't solve the issue.
