### ISSUE TITLE
Issue with chan.sankakucomplex.com

### ISSUE THREAD

**Issue by DarcMage** [fire015/adblocker-notice-removal#108]
https://chan.sankakucomplex.com/es/

Extension version: 1.2.35
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 OPR/100.0.0.0

Which country are you browsing from? [ANSWER HERE]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Unfortunately we cannot remove adblock notice from this site.
