### ISSUE TITLE
polytoria.com

### ISSUE THREAD

**Issue by RickGotTaken** [fire015/adblocker-notice-removal#109]
[This](https://github.com/fire015/adblocker-notice-removal/issues/106) is back.

**Comment by fire015** [comment]
I am still seeing it as blocked. Can you confirm the version of the extension?

**Comment by RickGotTaken** [comment]
1.2.35

**Comment by fire015** [comment]
Ok can you disable and enable the extension from chrome settings and then try again? I've seen an issue where it doesn't pick up the latest set of rules after an update for some reason.

**Comment by RickGotTaken** [comment]
That seems to have fixed it.
