### ISSUE TITLE
Issue with www.youtube.com

### ISSUE THREAD

**Issue by rickman785** [fire015/adblocker-notice-removal#111]
https://www.youtube.com/watch?v=8xM92pYFb3I

Extension version: 1.2.35
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Avast/116.0.0.0

Which country are you browsing from: united states
Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
<img width="960" alt="image" src="https://github.com/fire015/adblocker-notice-removal/assets/125222458/4cc18088-7436-4fe3-a52f-b0021f7dde2d">

**Comment by fire015** [comment]
Unfortunately if we remove this YouTube will stop videos from playing which could be confusing to our users if they can no longer see the adblock notice.
