### ISSUE TITLE
Issue with www.makeuseof.com

### ISSUE THREAD

**Issue by peterdsp** [fire015/adblocker-notice-removal#114]
https://www.makeuseof.com/mvc-mvp-mvvm-which-choose/

Extension version: 1.2.35
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

Which country are you browsing from? Greece

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
<img width="1901" alt="image" src="https://github.com/fire015/adblocker-notice-removal/assets/45949870/c69f724f-63c0-412c-b21b-88cff127250a">

**Comment by peterdsp** [comment]
Issue can be fixed, if you block this screen with your adblock , website keeps to work fine!

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
