### ISSUE TITLE
Issue with www.investing.com

### ISSUE THREAD

**Issue by adrjl** [fire015/adblocker-notice-removal#115]
https://www.investing.com/news/economy/romanias-economic-growth-expected-to-outpace-regional-average-says-allianz-trade-93CH-3191927

Extension version: 1.2.35
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60

<img width="1248" alt="Screenshot 2023-10-08 044326" src="https://github.com/fire015/adblocker-notice-removal/assets/147290814/7be79068-1cae-4be2-b8a2-46ec9ebd7d03">

Which country are you browsing from? [Netherlands]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Sorry I could not replicate this!
