### ISSUE TITLE
Issue with www.youtube.com Notifications not disappearing

### ISSUE THREAD

**Issue by Mochiman2** [fire015/adblocker-notice-removal#116]
https://www.youtube.com/watch?v=aqzpL0lc9Fc

Extension version: 1.2.36
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

Which country are you browsing from? [ANSWER HERE]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Cannot be removed see note in #119
