### ISSUE TITLE
Issue with www.onworks.net

### ISSUE THREAD

**Issue by cvfa1369** [fire015/adblocker-notice-removal#117]
https://www.onworks.net/runos/prepare-os.html

Extension version: 1.2.36
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Adblock:  Ghostery – Privacy Ad Blocker
Adblock version: 8.11.2
Which country are you browsing from? Canada
The operating system that i tried run in OnWorks (If Necessary): Ubuntu 22.04

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![Onworks Adblock Notice Screenshot](https://github.com/fire015/adblocker-notice-removal/assets/147667072/cb8e8f45-92c2-44f8-9425-66cd5262d49b)

**Comment by fire015** [comment]
Unfortunately removing the ad blocker leaves you unable to start a server, so its best that we leave this in place so as to not confuse users.
