### ISSUE TITLE
Issue with www.wordnik.com

### ISSUE THREAD

**Issue by rdeforest** [fire015/adblocker-notice-removal#118]
https://www.wordnik.com/words/gunwale

Extension version: 1.2.36
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

Which country are you browsing from? United States

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

![image](https://github.com/fire015/adblocker-notice-removal/assets/3655371/996b7b6c-5cdb-43e2-90b7-8d8a2ba37604)

I tried to block the message but its class is randomized and an attempt to block by the block-shadow property, which doesn't change between reloads, did not work.

I'm using uBlockOrigin v1.52.2

Thanks!

**Comment by rdeforest** [comment]
I kept fiddling with it and was able to block the message with the following in my uBlockOrigin filters:

`www.wordnik.com##link ~ div`

I know it's an ugly hack, but I leave it hear for others looking for temporary solutions. For those not familiar with CSS selectors, it hides any div preceded by a link sharing a direct parent with the div in question.

**Comment by fire015** [comment]
Yeh this is pretty hacky but thanks for looking. I am having a hard time figuring out what script is even injecting this.
