### ISSUE TITLE
Removing YouTube ad blocker notice

### ISSUE THREAD

**Issue by fire015** [fire015/adblocker-notice-removal#119]
## From the extension author:

We will not remove the YouTube ad blocker notice because doing so can prevent the video from playing.

This would be confusing to users of our extension if they no longer see the notice but can't play videos either.

Please direct your frustration at YouTube for this functionality :(

**Comment by rdeforest** [comment]
It may be worth noting that uBlockOrigin can still block YouTube ads without triggering the notice if the user follows the following steps:

1. Click uBlockOrigin icon in toolbar
1. Click "Open the dashboard", which looks like three gears as of Oct 2023
1. Select "Filter lists" tab
1. Click "Purge all caches" (has a clock symbol at the beginning of the button)
1. Click "Update now" (has a refresh symbol at the beginning of the button)

This has been working for me for weeks, but I have to repeat the procedure every day or two as Google and ad blockers play whack-a-mole.

**Comment by fire015** [comment]
FYI this also applies to dailymotion.com
