### ISSUE TITLE
Issue with www.youtube.com

### ISSUE THREAD

**Issue by Cypus-Skavenge** [fire015/adblocker-notice-removal#120]
https://www.youtube.com/watch?v=EXDGkvrgWX8

Extension version: 1.2.36
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

Which country are you browsing from? [America]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
<img width="958" alt="image" src="https://github.com/fire015/adblocker-notice-removal/assets/148375260/cb3e61fd-1c59-44ab-be38-cbe6126f78d0">

**Comment by fire015** [comment]
Cannot fix see #119 for details.
