### ISSUE TITLE
Issue with www.thequint.com

### ISSUE THREAD

**Issue by PlutarianReal** [fire015/adblocker-notice-removal#121]
https://www.thequint.com/tech-and-auto/tech-news/whatsapp-blocks-users-from-taking-screenshots-and-videos-of-view-once-messages-details-here#read-more

Extension version: 1.2.37
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

Which country are you browsing from? United States

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![allies](https://github.com/fire015/adblocker-notice-removal/assets/138826633/144a291a-4e98-4be7-8891-881e8acf3af0)

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
