### ISSUE TITLE
Issue with www.makeuseof.com

### ISSUE THREAD

**Issue by PlutarianReal** [fire015/adblocker-notice-removal#122]
https://www.makeuseof.com/ftdibus-sys-windows-disables-memory-integrity/

Extension version: 1.2.37
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

Which country are you browsing from? United States

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![iuseadblockerplus](https://github.com/fire015/adblocker-notice-removal/assets/138826633/7039f9c0-32ce-41e4-aee1-063214f03c39)

I use Ad Blocker Plus btw.

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
