### ISSUE TITLE
Issue with akwam.us

### ISSUE THREAD

**Issue by khabad** [fire015/adblocker-notice-removal#124]
https://akwam.us/search?q=la+casa+de+papel

Extension version: 1.2.37
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

Which country are you browsing from? [algeria]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![Screenshot 2023-10-22 192113](https://github.com/fire015/adblocker-notice-removal/assets/148715471/702b2302-cd6e-490b-8b64-08199db6fff8)

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
