### ISSUE TITLE
Issue with nsw2u.com

### ISSUE THREAD

**Issue by tistasis** [fire015/adblocker-notice-removal#125]
https://nsw2u.com/

Extension version: 1.2.37
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

Which country are you browsing from? [Mexico]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

![image](https://github.com/fire015/adblocker-notice-removal/assets/17823126/1b5ea615-58f9-4f24-8087-fcd5df24cd9c)

**Comment by fire015** [comment]
Try disable and enable the extension again (visit chrome://extensions/ in your browser).
