### ISSUE TITLE
Issue with xhamster.com

### ISSUE THREAD

**Issue by dspoke** [fire015/adblocker-notice-removal#127]
https://xhamster.com/

Extension version: 1.2.38
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

Which country are you browsing from? UK

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

<img width="1078" alt="Screenshot 2023-10-29 at 17 21 02" src="https://github.com/fire015/adblocker-notice-removal/assets/149324251/4f5f6e80-0cad-4622-838d-44d7942360d8">

**Comment by fire015** [comment]
Should be fixed in the next version, thanks!
