### ISSUE TITLE
Issue with www.zive.cz

### ISSUE THREAD

**Issue by NikdoCZ** [fire015/adblocker-notice-removal#128]
https://www.zive.cz/

Extension version: 1.2.38
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

Which country are you browsing from? [Czech republik
![Snímek obrazovky 2023-10-30 112657](https://github.com/fire015/adblocker-notice-removal/assets/38320098/b15871e6-240c-4b54-8057-19c953c5e349)
]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Should be fixed in the next version, thanks!
