### ISSUE TITLE
Issue with freecoursesite.com

### ISSUE THREAD

**Issue by imranext** [fire015/adblocker-notice-removal#129]
https://freecoursesite.com/complete-guide-to-freelancing-in-2023-zero-to-mastery/

Extension version: 1.2.39
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

Which country are you browsing from? [ANSWER HERE]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
