### ISSUE TITLE
Issue with slideshare.downloader.is

### ISSUE THREAD

**Issue by mdx079** [fire015/adblocker-notice-removal#131]
https://slideshare.downloader.is/

Extension version: 1.2.41
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

Which country are you browsing from? [Iraq]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
