### ISSUE TITLE
Issue with www.corriere.it

### ISSUE THREAD

**Issue by MS86ITA** [fire015/adblocker-notice-removal#134]
https://www.corriere.it/

Extension version: 1.2.43
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

Which country are you browsing from? ITALY

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

![image](https://github.com/fire015/adblocker-notice-removal/assets/151641893/bc9c93fe-d4c1-469f-9696-4fbfab7b6d86)

**Comment by fire015** [comment]
Will be fixed in the net version, thanks!
