### ISSUE TITLE
Issue with www.ilgazzettino.it

### ISSUE THREAD

**Issue by MS86ITA** [fire015/adblocker-notice-removal#135]
https://www.ilgazzettino.it/italia/primopiano/sciopero_27_novembre_nuovi_orari_quali_sono_dopo_precettazione_salvini-7776450.html

Extension version: 1.2.44
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

Which country are you browsing from? Italy

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

![image](https://github.com/fire015/adblocker-notice-removal/assets/151641893/8a1fe950-da68-4eb7-8c03-8680937e4fc4)

**Comment by fire015** [comment]
Sorry this is a paywall not an adblocker notice so cannot be removed.
