### ISSUE TITLE
Issue with www.investing.com

### ISSUE THREAD

**Issue by wail-shudar** [fire015/adblocker-notice-removal#136]
https://www.investing.com/news/stock-market-news/charlie-munger-dies-at-99-3245114

Extension version: 2.0.0
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0

Which country are you browsing from? [Brazil]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
@wail-shudar Do you have a screenshot? I am unable to replicate this.
