### ISSUE TITLE
Issue with www.digitalmusicnews.com

### ISSUE THREAD

**Issue by fran938** [fire015/adblocker-notice-removal#138]
https://www.digitalmusicnews.com/2023/05/15/which-artists-have-received-the-spotify-1-billion-streams-plaque/

Extension version: 2.0.0
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 OPR/104.0.0.0

Which country are you browsing from? [ANSWER HERE]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
