### ISSUE TITLE
Issue with mangoai.co

### ISSUE THREAD

**Issue by dark2385** [fire015/adblocker-notice-removal#139]
https://mangoai.co/

Extension version: 2.0.0
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

Which country are you browsing from? [IRAN]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![photo_2023-12-09_17-59-32](https://github.com/fire015/adblocker-notice-removal/assets/153374181/381bf312-bf4c-4ef7-8ce9-c2933c853fec)

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
