### ISSUE TITLE
Issue with puhutv.com

### ISSUE THREAD

**Issue by theakyol** [fire015/adblocker-notice-removal#141]
https://puhutv.com/kuzgun-3-bolum-izle

Extension version: 2.0.1
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0

Which country are you browsing from? [ANSWER HERE]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Sorry this cannot be removed as the video still will not play and therefore might be confusing to users.
