### ISSUE TITLE
Issue with nsw2u.net

### ISSUE THREAD

**Issue by Zel1nk** [fire015/adblocker-notice-removal#142]
https://nsw2u.net/

Extension version: 2.0.1
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

Which country are you browsing from? [MEXICO]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

![Sin título](https://github.com/fire015/adblocker-notice-removal/assets/154372200/7e9fd191-0e72-46be-b4fb-bb247bf094c6)

**Comment by fire015** [comment]
Will be fixed in the next version thanks!
