### ISSUE TITLE
Issue with www.op.gg

### ISSUE THREAD

**Issue by HudyHere** [fire015/adblocker-notice-removal#143]
https://www.op.gg/summoners/euw/Ikamerdnery-EUW

Extension version: 2.0.1
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0

Which country are you browsing from? Poland

![image](https://github.com/fire015/adblocker-notice-removal/assets/93191853/d9438713-9cc4-4b8d-9c95-83cae3a8d6bb)

**Comment by fire015** [comment]
Will be fixed in the next version thanks!
