### ISSUE TITLE
Issue with serkarijobresult.com

### ISSUE THREAD

**Issue by oF3L1Xo** [fire015/adblocker-notice-removal#144]
https://serkarijobresult.com/?lid=lVUEp&pid=864676&plid=12&vid=258661594

Extension version: 2.0.3
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

Which country are you browsing from? [ANSWER HERE]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

![image](https://github.com/fire015/adblocker-notice-removal/assets/146770936/58907261-ebc5-4712-be9d-8ef6c2664361)

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
