### ISSUE TITLE
Adblock still detected

### ISSUE THREAD

**Issue by troypurdieondatrack** [fire015/adblocker-notice-removal#145]
chrome://extensions/

Extension version: 2.0.3
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

Which country are you browsing from? [Vietnam]
![Screenshot (11)](https://github.com/fire015/adblocker-notice-removal/assets/154704732/fd10223e-4471-402d-bb9c-cdbdd181bac0)

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
