### ISSUE TITLE
Issue with aternos.org

### ISSUE THREAD

**Issue by VISHALUNNI** [fire015/adblocker-notice-removal#147]
https://aternos.org/software/

Extension version: 2.0.3
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0

Which country are you browsing from? [India]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

![image](https://github.com/fire015/adblocker-notice-removal/assets/108165471/08c876e7-ddfe-4579-ae95-d1ba1b97ec03)

**Comment by fire015** [comment]
Sorry its not possible to block on this site.
