### ISSUE TITLE
Issue with tutsnode.org

### ISSUE THREAD

**Issue by endlessg7** [fire015/adblocker-notice-removal#148]
https://tutsnode.org/

Extension version: 2.0.4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

Which country are you browsing from? [US]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![image](https://github.com/fire015/adblocker-notice-removal/assets/10377888/d4cb660c-6695-4a1b-b0b7-65d795b16c6e)

**Comment by fire015** [comment]
Wasn't able to remove from this site, too tricky without breaking the page!
