### ISSUE TITLE
Issue with perchance.org

### ISSUE THREAD

**Issue by rickman785** [fire015/adblocker-notice-removal#149]
https://perchance.org/ai-icon-generator

Extension version: 2.0.4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Avast/120.0.0.0

Which country are you browsing from? United States
<img width="948" alt="image" src="https://github.com/fire015/adblocker-notice-removal/assets/125222458/839d72de-2295-4af2-9340-83053d7a379f">

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Sorry we cannot remove this type of ad block.
