### ISSUE TITLE
Issue with www.dailymotion.com

### ISSUE THREAD

**Issue by NeroLee00** [fire015/adblocker-notice-removal#150]
https://www.dailymotion.com/video/x8rtqf8

Extension version: 2.0.4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

Which country are you browsing from? HK 

Please take a screenshot of the adblocker notice and drag and drop the image here if possible. 
(Sadly can't provide an image) The issue isn't that the adblock detection pop up didn't work, it's that the video keep pausing every other second as soon as I clicked unpause because the popup was gone.

**Comment by fire015** [comment]
You are right I am going to remove support for dailymotion as this interferes with the video (same problem as youtube). Will be fixed in the next version.
