### ISSUE TITLE
Issue with www.nflpenalties.com

### ISSUE THREAD

**Issue by TheKittyGuy** [fire015/adblocker-notice-removal#151]
https://www.nflpenalties.com/

Extension version: 2.0.4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

Which country are you browsing from? United States (Virginia)

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

Used my ad blocker to block the adblock message. It popped up though when I entered the site.

**Comment by fire015** [comment]
ill be fixed in the next version, thanks!
