### ISSUE TITLE
Issue with download.megaup.net

### ISSUE THREAD

**Issue by lopesroger** [fire015/adblocker-notice-removal#152]
https://download.megaup.net/?idurl=0lixLaV5L89JKamcHXUbendLHojcn8ukD9BC7JI75RXNNlSJnkAQnOYo2WZrfgY0WTeqkh4rGj2RRiaqGlb1MQiFzMs4X/tmMpEypQnFr20=&idfilename=Prince%20of%20Persia%20The%20Lost%20Crown%20[0100210019428000][v0][US].n%20sp.part1.rar&idfilesize=3.91%20GB

Extension version: 2.0.5
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

Which country are you browsing from? [ANSWER HERE]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Cannot be blocked on this site as removing the notice has no effect on the download.
