### ISSUE TITLE
Issue with www.spanishdict.com

### ISSUE THREAD

**Issue by pravindandekar** [fire015/adblocker-notice-removal#153]
https://www.spanishdict.com/

Extension version: 2.0.5
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 OPR/107.0.0.0 (Edition std-1)

Which country are you browsing from? [ANSWER HERE]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
