### ISSUE TITLE
Issue with tmail.io

### ISSUE THREAD

**Issue by yaschir** [fire015/adblocker-notice-removal#154]
https://tmail.io/temporary-disposable-gmail

Extension version: 2.0.6
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

Which country are you browsing from? [ANSWER HERE]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Sorry I am unable to replicate this, can you provide a screenshot and your location?
