### ISSUE TITLE
Issue with bnohpbaeckhhfnfijdnapgmbldkigchl

### ISSUE THREAD

**Issue by Wumbo-11** [fire015/adblocker-notice-removal#155]
chrome-extension://bnohpbaeckhhfnfijdnapgmbldkigchl/popup.html

Extension version: 2.0.6
User agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36

Which country are you browsing from? [Philippines]
![Screenshot_20240312-044548](https://github.com/fire015/adblocker-notice-removal/assets/105253613/552873ba-e84f-4870-86b8-9542e8326d5c)

**Comment by fire015** [comment]
Unfortunately removing this notice removes all of the content so it cannot be blocked.
