### ISSUE TITLE
Issue with www.photopea.com

### ISSUE THREAD

**Issue by SD-CD** [fire015/adblocker-notice-removal#156]
https://www.photopea.com/

Extension version: 2.0.6
User agent: 537.36 (KHTML, like Gecko) Chrome

Which country are you browsing from? [Canada]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![image](https://github.com/fire015/adblocker-notice-removal/assets/159513388/9124fa44-8268-48df-bea0-37acb8fe8b62)

**Comment by fire015** [comment]
Sorry we cannot block this as it breaks functionality if removed.
