### ISSUE TITLE
Issue with www.investing.com

### ISSUE THREAD

**Issue by FissionImpossible** [fire015/adblocker-notice-removal#157]
https://www.investing.com/equities

Extension version: 2.0.6
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

Which country are you browsing from? [Chile]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

![image](https://github.com/fire015/adblocker-notice-removal/assets/143339454/048def20-8c62-499d-bcb0-6198ee3d9ddf)

**Comment by fire015** [comment]
Sorry I am unable to replicate this.
