### ISSUE TITLE
Issue with www.sonyliv.com

### ISSUE THREAD

**Issue by damjien20** [fire015/adblocker-notice-removal#159]
https://www.sonyliv.com/shows/taarak-mehta-ka-ooltah-chashmah-1700000084/jethalal-ki-important-meeting-1000271872?watch=true

Extension version: 2.0.7
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

Which country are you browsing from? India

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Unfortunately we cannot remove on this site as doing so removes any content.
