### ISSUE TITLE
Issue with atozmath.com

### ISSUE THREAD

**Issue by Stagnantwater949** [fire015/adblocker-notice-removal#161]
https://atozmath.com/CONM/NumeInterPola.aspx?q=DD&q1=1%60300%2C304%2C305%2C307%602.4771%2C2.4829%2C2.4843%2C2.4871%3B%60301%60DD%601&dp=8&tm=R&do=1

Extension version: 2.0.7
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

Which country are you browsing from? [INDIA]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![image](https://github.com/fire015/adblocker-notice-removal/assets/129622184/72b50783-5bbf-4af8-9297-4577480febdd)

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
