### ISSUE TITLE
Issue with playon2.gamezone.cam

### ISSUE THREAD

**Issue by aliMustafa52** [fire015/adblocker-notice-removal#163]
https://m.asd.quest/%d9%81%d9%8a%d9%84%d9%85-dune-part-two-2024-%d9%85%d8%aa%d8%b1%d8%ac%d9%85/

Extension version: 2.0.8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

Which country are you browsing from? Netherlands

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![Screenshot_27](https://github.com/fire015/adblocker-notice-removal/assets/104281551/f53c742b-391b-4935-b393-4dd6ce1c6331)
![Screenshot_26](https://github.com/fire015/adblocker-notice-removal/assets/104281551/7acec6af-9feb-4d1c-ad6f-15d78667f9a4)

**Comment by fire015** [comment]
Should be fixed in the next version, thanks!
