### ISSUE TITLE
Issue with xhamster.com

### ISSUE THREAD

**Issue by dspoke** [fire015/adblocker-notice-removal#164]
https://github.com/fire015/adblocker-notice-removal/issues/127

Extension version: 2.0.8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

Which country are you browsing from? UK

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![Screenshot 2024-06-10 at 04 00 58](https://github.com/fire015/adblocker-notice-removal/assets/149324251/c7e1b34f-4fa6-4156-b9ec-0ac9967da293)

**Comment by fire015** [comment]
We cannot block this due to Chrome store policies.
