### ISSUE TITLE
Issue with www.pornhub.com

### ISSUE THREAD

**Issue by dspoke** [fire015/adblocker-notice-removal#165]
https://www.pornhub.com/

Extension version: 2.0.8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

Which country are you browsing from? UK

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![Screenshot 2024-06-10 at 04 04 22](https://github.com/fire015/adblocker-notice-removal/assets/149324251/70f71b85-828b-4447-9359-b7c67d6ac6e5)

**Comment by fire015** [comment]
We cannot block this due to Chrome store policies.
