### ISSUE TITLE
Reporting an issue with site

### ISSUE THREAD

**Issue by Rajmundzik** [fire015/adblocker-notice-removal#20]
https://www.money.pl/

here your extension does not work
It would be helpful to update your adblocker
Thanks in advance

**Comment by fire015** [comment]
Hi @Rajmundzik, I am unable to see this using the link provided.

Please visit the page and view the adblock notice, then right-click the notice and select "Inspect".

Once you can see the developer toolbar and the notice on your screen, take a screenshot and upload it here.

Thanks :)
