### ISSUE TITLE
Ad Blocker Notice - https://www.speedrun.com/

### ISSUE THREAD

**Issue by LouisCasillas** [fire015/adblocker-notice-removal#22]
Found a website with an ad blocker notice.

Using the latest Chrome browser and opened page in an incognito window with only the 'Ad Blocker Notice Removal' extension enabled.

Site: https://www.speedrun.com/

**Comment by fire015** [comment]
Hi @LouisCasillas I am unable to see this using the link provided.

Please visit the page and view the adblock notice, then right-click the notice and select "Inspect".

Once you can see the developer toolbar and the notice on your screen, take a screenshot and upload it here.

Thanks :)

**Comment by LouisCasillas** [comment]
![image](https://user-images.githubusercontent.com/9426386/176221717-80713faf-ec53-4399-bb95-4a97c4977d70.png)

**Comment by fire015** [comment]
Sorry this doesn't help as much as I would have liked. Unfortunately I cannot replicate this, however you are welcome to submit a pull request and fix it yourself (details in the `Adding/Editing Website Rules` section of the README). Thanks
