### ISSUE TITLE
Ad Blocker Notice - sltrib.com

### ISSUE THREAD

**Issue by LouisCasillas** [fire015/adblocker-notice-removal#23]
Example URL: https://www.sltrib.com/religion/2021/01/28/latest-mormon-land-how/#:~:text=%E2%80%9CFold%20my%20arms%20and%20bow%20my%20head%20%E2%80%9CAnd,in%20a%20recent%20By%20Common%20Consent%20blog%20post.

![image](https://user-images.githubusercontent.com/9426386/176222011-ecbd6a02-792f-4d04-b313-faef44197006.png)

**Comment by fire015** [comment]
This will be fixed in the next version. Thanks!
