### ISSUE TITLE
adblock does not work?

### ISSUE THREAD

**Issue by Larneman** [fire015/adblocker-notice-removal#25]
https://filecr.com/elearning/wordpress-for-beginners/?id=115728010092

**Comment by fire015** [comment]
Hi, I am unable to see this using the link provided.

Please visit the page and view the adblock notice, then right-click the notice and select "Inspect".

Once you can see the developer toolbar and the adblock notice on your screen, take a screenshot and upload it here (drag and drop the image file into the comment box).

Thanks :)
