### ISSUE TITLE
Doesn't work on onlysky.media

### ISSUE THREAD

**Issue by LoganBlackisle** [fire015/adblocker-notice-removal#27]
https://onlysky.media/author/bSeidensticker/?mc_cid=9cad56a273&mc_eid=050ff66981

It worked when I installed the extension a few days ago, but now it doesn't.

![Screenshot](https://user-images.githubusercontent.com/47138186/180480409-2ffc90df-f92f-4388-a143-f05a9324bda3.png)

**Comment by fire015** [comment]
@LoganBlackisle that's a strange one, I don't see that message only this below (which I have now fixed in the next version):

<img width="916" alt="Screenshot 2022-07-23 at 12 04 46" src="https://user-images.githubusercontent.com/501743/180602505-e170047c-e061-4e17-8adf-d72f4e1f775b.png">
