### ISSUE TITLE
Stop showing ads

### ISSUE THREAD

**Issue by Antesh1** [fire015/adblocker-notice-removal#37]
Dear Sir,

I am writing to you because I found something wrong with your exetention. On my browser, testbook.com showing the ads. Please stop showing ads on the site as it is not working.

**Comment by fire015** [comment]
Hi, I am unable to see this using the link provided.

Please visit the page and view the adblock notice, then right-click the notice and select "Inspect".

Once you can see the developer toolbar and the adblock notice on your screen, take a screenshot and upload it here (drag and drop the image file into the comment box).

Thanks :)
