### ISSUE TITLE
investing.com

### ISSUE THREAD

**Issue by zombiehoffa** [fire015/adblocker-notice-removal#4]
https://www.investing.com/equities/kinaxis-inc

has a popup adblocker notice that this plugin didn't catch.

**Comment by fire015** [comment]
Hi, I am unable to see this using the link provided.

Please visit the page and view the adblock notice, then right-click the notice and select "Inspect".

Once you can see the developer toolbar and the notice on your screen, take a screenshot and upload it here.

Thanks :)

**Comment by zombiehoffa** [comment]
I think it might not be this plugin afterall. Once I disabled brave's ad blocking (but kept this plugin and ublock origin going) the ads and the notice were both gone. Sorry for the time waste.

**Comment by fire015** [comment]
No problem :)
