### ISSUE TITLE
Ad Blocker Notice

### ISSUE THREAD

**Issue by Ambki319** [fire015/adblocker-notice-removal#40]
Hello! I need help that when I tried to read a e-book on this site, i don't get it why it detects Ad Blocker though I did all to remove an ad block. I hope you can help me, thank you.
![image](https://user-images.githubusercontent.com/120432462/207204735-c86a72db-d277-4407-afae-a79928c9c983.png)

**Comment by fire015** [comment]
Sorry, we cant block this due to the methods used by the site to avoid detection.
