### ISSUE TITLE
Issue with website

### ISSUE THREAD

**Issue by Jwong5590** [fire015/adblocker-notice-removal#43]
Drakescans.com
![image](https://user-images.githubusercontent.com/122408319/211673270-dd0bb89b-b149-44e6-b78e-f5645a7e1285.png)
It not blocking the adblocker

**Comment by fire015** [comment]
@Jwong5590 I am seeing a different ad block message entirely. Is this screenshot recent? Also can you confirm the full URL (starting with http) as the drakescans.com page I see the logo looks different to the screenshot.

**Comment by fire015** [comment]
I have made a fix for the ad block that I can see.
