### ISSUE TITLE
Issue with website

### ISSUE THREAD

**Issue by panchozelada** [fire015/adblocker-notice-removal#46]
https://solowrestling.mundodeportivo.com/new/116760-wwe-smackdown-planes-3-febrero-2023?fbclid=IwAR01Pag8g_rSpalsrCasPEAgk0k3O1TDqdRIIN10eRjzSHly-0KajPKxah0

![image](https://user-images.githubusercontent.com/75702147/216713887-2fbf6c76-9ff2-4f22-a80b-99a431601fbb.png)

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
