### ISSUE TITLE
Issue with website

### ISSUE THREAD

**Issue by tycooko** [fire015/adblocker-notice-removal#49]
https://www.hindustantimes.com/technology/this-supersonic-aircraft-will-take-you-from-new-york-to-london-in-just-80-minute-101664536746706.html

<img width="1789" alt="Screenshot 2023-02-13 at 13 15 20" src="https://user-images.githubusercontent.com/75950926/218455169-e10de8f7-9968-4699-9802-1df7dda7b23a.png">

**Comment by fire015** [comment]
Thanks will be fixed in the next version!
