### ISSUE TITLE
Extension does not work on the site I installed it for

### ISSUE THREAD

**Issue by psydex** [fire015/adblocker-notice-removal#5]
There's this website for movies that once you click the player to play a movie it pops up an adblock enabled warning which this extension did not bypass. 

https://filmisub.com/

**Comment by fire015** [comment]
Hi, I am unable to see this using the link provided.

Please visit the page and view the adblock notice, then right-click the notice and select "Inspect".

Once you can see the developer toolbar and the notice on your screen, take a screenshot and upload it here.

Thanks :)
