### ISSUE TITLE
Still get adblocker notice on this site

### ISSUE THREAD

**Issue by tma-0** [fire015/adblocker-notice-removal#50]
https://camerajabber.com/how-do-you-use-olympus-live-nd-shooting-mode/

Please provide more details here including any screenshots
![Screenshot 2023-02-19 16 51 11](https://user-images.githubusercontent.com/110162257/219959056-fa45004d-0e1e-4700-bcc1-f0589bbe376c.png)

**Comment by fire015** [comment]
Thanks will be fixed in the next version!
