### ISSUE TITLE
Issue with website

### ISSUE THREAD

**Issue by Peter-Go** [fire015/adblocker-notice-removal#53]
https://www.calvyn.com/cisco-881-router-with-pppoe-connection-over-external-adsl-modem/

Please provide more details here including any screenshots

![image](https://user-images.githubusercontent.com/13273395/224661088-2089e66f-96ff-42c6-aa9e-965e343a9e2e.png)

**Comment by fire015** [comment]
Sorry due to techniques used by this site it is not possible to block this.
