### ISSUE TITLE
Issue with Mac Torrents

### ISSUE THREAD

**Issue by tycooko** [fire015/adblocker-notice-removal#57]
https://www.torrentmac.net/?s=acrobat

<img width="1243" alt="Screenshot 2023-04-05 at 12 41 52" src="https://user-images.githubusercontent.com/75950926/230057891-5f3d0e44-e99b-478a-a1f4-24ee6e4e94cb.png">

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
