### ISSUE TITLE
Issue with website

### ISSUE THREAD

**Issue by gorgulenkozxc** [fire015/adblocker-notice-removal#58]
https://www.gutefrage.net/frage/wann-sagt-man-ich-binjahre-alt-und-wann-sagt-man-ich-binjahre-jung

![image](https://user-images.githubusercontent.com/92183497/230358546-1aba99e3-aba1-4ad5-8b38-e0e496f188e0.png)

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
