### ISSUE TITLE
Issue with website

### ISSUE THREAD

**Issue by Hatred-Ov-The-Human-Race** [fire015/adblocker-notice-removal#59]
https://filecr.com/windows/imobie-anytrans-for-ios/?id=183074303952

Please provide more details here including any screenshots

**Comment by Hatred-Ov-The-Human-Race** [comment]
i dont have a way to do screen shots but it doesnt work please fix love the website but ads evil evil ads

**Comment by fire015** [comment]
Sorry I cannot replicate this. Which country are you browsing from and which adblocker extension do you use?

**Comment by fire015** [comment]
It looks like this ad block only appears when you click download, this is not something we can bypass I am afraid.
