### ISSUE TITLE
Issue with website

### ISSUE THREAD

**Issue by Optimus8254** [fire015/adblocker-notice-removal#60]
![Ekran görüntüsü 2023-04-16 134108](https://user-images.githubusercontent.com/116325755/232300302-88a6cc85-df69-41a0-b39e-f4ced4faa15a.png)
https://filecr.com/windows/content-grabber/?id=114880706794

Please provide more details here including any screenshots

**Comment by fire015** [comment]
Sorry I cannot replicate this. Which country are you browsing from and which adblocker extension do you use?
