### ISSUE TITLE
Issue with website

### ISSUE THREAD

**Issue by julianwright55** [fire015/adblocker-notice-removal#62]
https://nanimex1.com/episode/kono-yo-no-hate-de-koi-wo-utau-shoujo-yu-no-episode-003/
![image](https://user-images.githubusercontent.com/97090104/232563084-d56a8446-444b-4eb6-aec1-5866127eb203.png)

Please provide more details here including any screenshots

**Comment by fire015** [comment]
Sorry this type of functionality is not supported.
