### ISSUE TITLE
Issue with website

### ISSUE THREAD

**Issue by tycooko** [fire015/adblocker-notice-removal#68]
https://crast.net/32800/these-are-the-pros-and-cons-of-hydrogel-to-protect-the-screen-of-your-ios-or-android-mobile/

I'm in Barcelona, Spain.
<img width="1992" alt="Screenshot 2023-05-01 at 11 59 17" src="https://user-images.githubusercontent.com/75950926/235438032-c5c1543a-5aa0-43a7-b727-020e1c315833.png">

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
