### ISSUE TITLE
Issue with nsw2u.com

### ISSUE THREAD

**Issue by AlejandroR55** [fire015/adblocker-notice-removal#81]
https://nsw2u.com/

Which country are you browsing from? United States

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![image](https://github.com/fire015/adblocker-notice-removal/assets/29897316/efe800b8-4d9a-4bb0-b28e-8faa39b01b72)

**Comment by fire015** [comment]
Should be fixed in the next version, thanks!
