### ISSUE TITLE
Issue with www.techgeeknext.com

### ISSUE THREAD

**Issue by ansuman13** [fire015/adblocker-notice-removal#82]
https://www.techgeeknext.com/exportpdfs#:~:text=Use%20GET%20method%20with%20end,and%20download%20the%20PDF%20document.

Which country are you browsing from? [USA]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Should be fixed in the next version, thanks!
