### ISSUE TITLE
Issue with emoji.gg

### ISSUE THREAD

**Issue by Shykuzo** [fire015/adblocker-notice-removal#83]
https://emoji.gg/

Which country are you browsing from? Belgium

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![Screenshot_20230629_053454](https://github.com/fire015/adblocker-notice-removal/assets/79150204/13a2945a-ea15-4e0d-ade0-6de7c601acc6)

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
