### ISSUE TITLE
Issue with www.samsungoneui.com

### ISSUE THREAD

**Issue by logobg** [fire015/adblocker-notice-removal#84]
https://www.samsungoneui.com/tips/how-to-install-android-13-stock-rom-on-samsung-galaxy-s20-5g/

Which country are you browsing from? [Austria]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![image](https://github.com/fire015/adblocker-notice-removal/assets/3891665/d14f3790-b8e5-4954-a96a-a55d3a9c129c)

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
