### ISSUE TITLE
Issue with aternos.org

### ISSUE THREAD

**Issue by Someone68** [fire015/adblocker-notice-removal#85]
https://aternos.org/server

Which country are you browsing from? United States

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![image](https://github.com/fire015/adblocker-notice-removal/assets/97077158/384aed0f-a3cd-4c51-a6ee-b22928a309ea)

**Comment by fire015** [comment]
Sorry I have been unable to replicate this :(
