### ISSUE TITLE
Issue with www.xda-developers.com

### ISSUE THREAD

**Issue by logobg** [fire015/adblocker-notice-removal#89]
https://www.xda-developers.com/best-docking-stations-lenovo-thinkpad-x1-nano-gen-3/

Which country are you browsing from? Austria

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![image](https://github.com/fire015/adblocker-notice-removal/assets/3891665/fe0aca54-ed82-4254-afe4-de99c9ea469f)

**Comment by fire015** [comment]
Should be fixed in the next version, let me know if you still have issues after version 1.2.28
