### ISSUE TITLE
Issue with vakilsearch.com

### ISSUE THREAD

**Issue by nikhilpal-cogoport** [fire015/adblocker-notice-removal#90]
https://vakilsearch.com/blog/how-much-does-it-cost-register-opc-india/#

Which country are you browsing from? [ANSWER HERE]

Please take a screenshot of the adblocker notice and drag and 
<img width="972" alt="Screenshot 2023-07-25 at 9 04 42 AM" src="https://github.com/fire015/adblocker-notice-removal/assets/125271159/94811bdc-bc13-4c91-8d17-8177c919d047">
drop the image here if possible.

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
