### ISSUE TITLE
Issue with work.ink

### ISSUE THREAD

**Issue by NickSneaky** [fire015/adblocker-notice-removal#94]
https://work.ink/1A1/carcrusher2

Which country are you browsing from? Romania

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![image](https://github.com/fire015/adblocker-notice-removal/assets/70890575/6aa4c30e-58dd-4816-aef0-cd9f143a7505)

**Comment by fire015** [comment]
Unfortunately the website removes all of the content on the page when it shows this notice so there would be no point in blocking this as it would be too late.
