### ISSUE TITLE
Issue with work.ink

### ISSUE THREAD

**Issue by oiqojhowbo** [fire015/adblocker-notice-removal#95]
https://work.ink/2vm/gwiMMejd91w

Extension version: 1.2.29

Which country are you browsing from? [Philippines
![Screenshot 2023-08-08 110735](https://github.com/fire015/adblocker-notice-removal/assets/141698553/4e1348b1-c9fd-4e34-a626-e2708c678f6a)
]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Unfortunately the website removes all of the content on the page when it shows this notice so there is nothing we can do about this.
