### ISSUE TITLE
Issue with coursesdaddy.com

### ISSUE THREAD

**Issue by sayyadsajjad** [fire015/adblocker-notice-removal#96]
https://coursesdaddy.com/code-mosh-ultimate-html-css-mastery-series-123-free-download/#google_vignette

Extension version: 1.2.29

Which country are you browsing from? [ANSWER HERE]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
