### ISSUE TITLE
Issue with aternos.org

### ISSUE THREAD

**Issue by NickSneaky** [fire015/adblocker-notice-removal#97]
https://aternos.org/server/

Which country are you browsing from? Romania

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![image](https://github.com/fire015/adblocker-notice-removal/assets/70890575/fd20f01c-aff0-4004-b588-33eb4a589d2b)

**Comment by fire015** [comment]
Sorry I have been unable to replicate this.
