### ISSUE TITLE
Issue with www.shaalaa.com

### ISSUE THREAD

**Issue by Noname123123322** [fire015/adblocker-notice-removal#98]
https://www.shaalaa.com/question-bank-solutions/explain-the-following-concept-non-alignment-effects-of-the-cold-war_77645#ref=chapter&id=62879

Extension version: 1.2.30

Which country are you browsing from? [INDIA]

Please take a screenshot of the adblocker notice and drag and drop the image here if possible.
![Web capture_12-8-2023_163519_www shaalaa com](https://github.com/fire015/adblocker-notice-removal/assets/87407880/df288b1a-0d76-4f0d-9261-ef6d798883bd)

**Comment by fire015** [comment]
Will be fixed in the next version, thanks!
